import type { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/session";
import prisma from "@/lib/prisma";
import { elseThrow } from "@/lib/errors";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function ApplicationLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const pathname = headers().get("x-invoke-path") ?? "";

	const user = await getCurrentUser();

	if (!user) {
		redirect("/sign-in");
	}

	let profile: Awaited<ReturnType<typeof prisma.profile.findUnique>> | null = await prisma.profile.findUnique({
		where: {
			id: user.id,
		},
	});

	if (!profile) {
		// try {
		// 	profile = await prisma.profile.create({
		// 		data: {
		// 			userId: (await prisma.user.findUnique({
		// 				where: {
		// 					email: user.email ?? ""
		// 				}
		// 			}) ?? elseThrow("User not found")).id
		// 		}
		// 	})
		// } catch (err) {
		// 	console.error(err)
		// 	throw new Error("Something went wrong")
		// }
		redirect("/onboarding")
	}

	if (
			profile.role === "NONE" &&
			!pathname.startsWith("/onboarding")
	) {
		redirect("/onboarding");
	}

	return (
		<div className="flex justify-center w-full h-auto min-h-rem-screen">
			{/* <Sidebar /> */}
			<div className="flex justify-center w-full p-8">{children}</div>
		</div>
	);
}
