import type { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/session";
import prisma from "@/lib/prisma";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function ApplicationLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const pathname = headers().get("x-invoke-path") ?? "";

	const user = await getCurrentUser();

	if (!user) {
		redirect("/sign-in");
	}

	const profile = await prisma.profile.findUnique({
		where: {
			id: user.id,
		},
	});

	if (
		(!profile && !pathname.startsWith("/onboarding")) ||
		(profile &&
			profile.role === "NONE" &&
			!pathname.startsWith("/onboarding"))
	) {
		redirect("/onboarding");
	}

	return (
		<div className="flex justify-center w-full h-auto min-h-rem-screen">
			{/* <Sidebar /> */}
			<div className="flex justify-center w-full p-8">{children}</div>
		</div>
	);
}
