import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import NextUIProvider from "@/context/NextUI";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<AuthProvider>
			<html lang="en">
				<body className={inter.className}>
					<NextUIProvider>
						<Toaster position="bottom-right" />
						<Navbar />
						<div className="w-full h-auto min-h-rem-screen">
							{children}
						</div>
					</NextUIProvider>
				</body>
			</html>
		</AuthProvider>
	);
}
