import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/session";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function Auth({
	children,
}: {
	children: React.ReactNode;
}) {
	const user = await getCurrentUser();

	if (user) {
		redirect("/onboarding");
	}

	return (
		<div className="flex justify-center w-full h-auto min-h-rem-screen">
			{children}
		</div>
	);
}
